# Generated by Django 4.1.5 on 2023-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistersUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
